#spring.cloud.gcp.project-id=hmd-gen-api
#spring.cloud.gcp.credentials.location=file:/home/leo/Downloads/hmd-gen-api-33ea875cc794.json
#spring.cloud.gcp.firestore.enabled=true
#spring.cloud.gcp.firestore.auto-create-indices=true